### ISSUE TITLE
Important issue

### ISSUE THREAD

**Issue by nassima200** [phyunsj/node-red-dashboard-login#4]
If I'm signed in from one device I find myself automatically signed in other devices

**Comment by baha00** [comment]
this is because this is not actual login or session. There is no auth cookie or anything similar. When you login you actually change settings on groups visibility so this settings are changed for any used or any device. 
This could be resolved -in theory that session cookie is issued after login, and  that session cookie is asked on page load... if session cookie found= True login=false if not found asks for login...  
Unfortunately I dont know how to put that in practice

**Comment by phyunsj** [comment]
Please read section "Multiple Users" from https://flows.nodered.org/node/node-red-dashboard.
You can also find similar topic by googling. 

If you check msg object out of "Dashboard Sing-in" node, you will see socketid property. This value should be passed down to ui-control ""5c0b7126.396e8"(Go to Sensor/History Group) in order to work with the current flow. 

Ultimately socketid has be managed by node-red-dashboard (ui.js) and make emit functions  operational if socketid is valid.  (session timeout, logout) should clear socketid.

**Comment by phyunsj** [comment]
README is updated with new flow.  I was trying to make as little as possible for node-red-dashboard changes. Unfortunately it was necessary to make it work.

Thank you for catching it. Otherwise, I won't know about it.

**Comment by nassima200** [comment]
> README is updated with new flow. I was trying to make as little as possible for node-red-dashboard changes. Unfortunately it was necessary to make it work.
> 
> Thank you for catching it. Otherwise, I won't know about it.

Thank you! It work much better now
